function strpos(haystack,needle,offset){var i=(haystack+'').indexOf(needle,(offset||0));return i===-1?false:i;}
function setCookie(name,value,time){var expires=new Date();expires.setTime(expires.getTime()+time);document.cookie=name+'='+value+'; expires='+expires.toGMTString();}
function getCookie(name){var cookies=document.cookie.toString().split('; ');var cookie,c_name,c_value;for(var n=0;n<cookies.length;n++){cookie=cookies[n].split('=');c_name=cookie[0];c_value=cookie[1];if(c_name==name){return c_value;}}
return null;}
String.prototype.decodeHTML=function(){var map={"gt":">"};return this.replace(/&(#(?:x[0-9a-f]+|\d+)|[a-z]+);?/gi,function($0,$1){if($1[0]==="#"){return String.fromCharCode($1[1].toLowerCase()==="x"?parseInt($1.substr(2),16):parseInt($1.substr(1),10));}else{return map.hasOwnProperty($1)?map[$1]:$0;}});};function getContentFolder(url){url=url.toLowerCase();ord=url.charCodeAt(0);if(ord>=48&&ord<=57){return"a";}else if(ord>=97&&ord<=122){return url.charAt(0);}else{return"_";}}
var sugg=[["xxx_xxx","Xxx xxx"],["yyy_yyy","Yyy yyy"]];var se_su=false;function autocomplete(inp){var currentFocus;inp.addEventListener("input",function(e){var a,b,i,val=this.value;closeAllLists();if(!se_su){var d=new Date();$.getScript(FGdomain+"/ajax/search_tokens.js?"+d.getYear()+''+d.getMonth()+''+d.getDate(),function(){sugg=t;});se_su=true;}
if(!val){return false;}
if(val.length<3){return false;}
currentFocus=-1;currentFocus=-3;a=document.createElement("DIV");a.setAttribute("id",this.id+"autocomplete-list");a.setAttribute("class","autocomplete-items");this.parentNode.appendChild(a);for(i=0;i<sugg.length;i++){sugh=sugg[i];sugh[1]=sugh[1].decodeHTML();if(sugh[1].toUpperCase().includes(val.toUpperCase())){b=document.createElement("DIV")
b.innerHTML="<a href='/"+FGgames+"/"+sugh[0]+"'><div class='img-icon'><img src='//fgn.cdn.serverable.com/common/flashes/small/"+getContentFolder(sugh[0])+"/"+sugh[0]+".jpg'></div></a>";var n=sugh[1].toUpperCase().indexOf(val.toUpperCase());var n2=n+val.length;b.innerHTML+="<a href='/"+FGgames+"/"+sugh[0]+"'><div class='tocken_name'>"+sugh[1].substr(0,n)+"<strong>"+sugh[1].substr(n,val.length)+"</strong>"+sugh[1].substr(n2)+"</div></a>";b.innerHTML+="<input type='hidden' value='"+sugh[1]+"'></a>";b.addEventListener("click",function(e){inp.value=this.getElementsByTagName("input")[0].value;document.location.href=this.getElementsByTagName("a")[0].href;closeAllLists();});a.appendChild(b);}}});inp.addEventListener("keydown",function(e){var x=document.getElementById(this.id+"autocomplete-list");if(x)x=x.getElementsByTagName("div");if(e.keyCode==40){currentFocus++;currentFocus++;currentFocus++;addActive(x);}else if(e.keyCode==38){currentFocus--;currentFocus--;currentFocus--;addActive(x);}else if(e.keyCode==13){if(currentFocus!=-3){e.preventDefault();if(currentFocus>-1){if(x)x[currentFocus].click();}}}});function addActive(x){if(!x)return false;removeActive(x);if(currentFocus>=x.length)currentFocus=0;if(currentFocus<0)currentFocus=(x.length-1);x[currentFocus].classList.add("autocomplete-active");}
function removeActive(x){for(var i=0;i<x.length;i++){x[i].classList.remove("autocomplete-active");}}
function closeAllLists(elmnt){var x=document.getElementsByClassName("autocomplete-items");for(var i=0;i<x.length;i++){if(elmnt!=x[i]&&elmnt!=inp){x[i].parentNode.removeChild(x[i]);}}}
document.addEventListener("click",function(e){closeAllLists(e.target);});}
$(document).ready(function(){$("#myInput").one("focus",function(){autocomplete(document.getElementById("myInput"));});$('.list_sideBar .title').click(function(){$(this).next('.list_sideBar .list').slideToggle();$(this).toggleClass('open');$(this).find('i').toggleClass('fa-angle-up');});$('.open_sidebar').click(function(){$('.list_sideBar').addClass('open');});$('.close_sidebar').click(function(){$('.list_sideBar').removeClass('open');});$('.search_toggle').click(function(){$('.searchArea').slideToggle();});$('.bfh-selectbox').on('change.bfhselectbox',function(){var lang=$(this).val();href=$('a[data-code="'+lang+'"]').attr('href');window.location.href=href;});$("#subscribeFormForm").submit(function(e){e.preventDefault();var form=$(this);var actionUrl=form.attr('action');$.ajax({type:"POST",url:actionUrl,data:form.serialize(),success:function(data)
{alert(data);}});});});jQuery.cachedScript=function(url,options){options=$.extend(options||{},{dataType:"script",cache:true,url:url});return jQuery.ajax(options);};loadCSS=function(href){var cssLink=$("<link>");$("head").append(cssLink);cssLink.attr({rel:"stylesheet",type:"text/css",href:href});};var isDirty=false;window.onload=function(){window.addEventListener("beforeunload",function(e){if(!isDirty){return undefined;}
var confirmationMessage='It looks like you have been editing something. '
+'If you leave before saving, your changes will be lost.';(e||window.event).returnValue=confirmationMessage;return confirmationMessage;});};$(document).ready(function(){document.getElementById('myInput').onkeypress=function(){document.getElementById('myInput').value=document.getElementById('myInput').value.replace("”",'"').replace("“",'"').replace("’","'").replace("‘","'").replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/[\u2026]/g,'...');};});if(window.matchMedia("(max-width: 576px)").matches){$('iframe.d-sm-none').each(function(){$(this).attr('src',$(this).data('src'))});}
if(window.matchMedia("(min-width: 768px)").matches){$('iframe.d-md-block').each(function(){$(this).attr('src',$(this).data('src'))});}
if(window.matchMedia("(min-width: 1200px)").matches){$('iframe.d-xl-block').each(function(){$(this).attr('src',$(this).data('src'))});}
(function($){function generateStars(){$('.tsm-stars').each(function(){const $stars=$(this);const rating=parseInt($stars.data('rating'),10)||5;const starHtml='<svg class="tsm-star" aria-hidden="true"><use href="#tsm-star-icon"></use></svg>';$stars.attr('aria-label',rating+' star rating');for(let i=0;i<rating;i++){$stars.append($(starHtml));}});}
const CLAMP='tsm-clamp';const EXP='tsm-expanded';const MORE='tsm-readmore';function needsReadMore($el){const clampedHeight=$el.height();$el.removeClass(CLAMP);const fullHeight=$el.height();$el.addClass(CLAMP);return fullHeight>clampedHeight+2;}
function addButton($el){const $btn=$('<button>').attr('type','button').addClass(MORE).text('Read more');$btn.on('click',function(){const expanded=$el.toggleClass(EXP).hasClass(EXP);if(expanded){$el.removeClass(CLAMP);$btn.text('Read less');}else{$el.addClass(CLAMP);$btn.text('Read more');}});$el.after($btn);}
$(document).ready(function(){generateStars();$('.tsm .tsm-quote').each(function(){const $p=$(this);if(!$p.hasClass(EXP)){$p.addClass(CLAMP);}
if(needsReadMore($p)){addButton($p);}});});})(jQuery);function strpos(haystack,needle,offset){var i=(haystack+'').indexOf(needle,(offset||0));return i===-1?false:i;}
function setCookie(name,value,time){var expires=new Date();expires.setTime(expires.getTime()+time);document.cookie=name+'='+value+'; expires='+expires.toGMTString();}
function getCookie(name){var cookies=document.cookie.toString().split('; ');var cookie,c_name,c_value;for(var n=0;n<cookies.length;n++){cookie=cookies[n].split('=');c_name=cookie[0];c_value=cookie[1];if(c_name==name){return c_value;}}
return null;}